[server]
headless = true

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#E9643B"
backgroundColor = "#FBF1E4"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#2E2016"
font = "sans serif"